### ISSUE TITLE
start processor: tax stop working without message?

### ISSUE THREAD

**Issue by tommy83** [firegento/firegento-magesetup2#113]
### General
* fresh setup of Magento 2.2.3
* * * 50000 sample products

### Issue description
After starting
`bin/magento magesetup:setup:run de`
we gett message:
`start processor: tax`

But not it stucks. We wait 3 hours. But it seems start processor: tax stops working without error/message.
How long we have to wait?

### Steps to reproduce
start: putty/ssh
enter:
```
composer config repositories.firegento_magesetup vcs git@github.com:firegento/firegento-magesetup2.git
composer require firegento/magesetup2:dev-develop
bin/magento module:enable FireGento_MageSetup
bin/magento setup:upgrade
bin/magento magesetup:setup:run de
```

**Comment by rechengehirn** [comment]
Could you solve this problem? I'm having the same.

**Comment by helmuthva** [comment]
Same problem.

**Comment by helmuthva** [comment]
Update: it eventually finished after 45 minutes for ~2000 products (running on a Macbook Pro)

**Comment by hawkeyevc** [comment]
I am currently working on this problem, because we have currently a migration coming fom 1.9.3.. It has to do with the still very slow save of complete products. 
The black magick happends in `private function saveTaxClassRelations($taxClasses)` in class TaxSubProcessor. All products were looped and modified and saved. It is not necessary to save the whole product. But I have to test my modifications first (I use the hints from here: https://mage2-blog.com/magento-2-speed-up-product-save/) 
I will try to give a patch for this stuff soon.

**Comment by sprankhub** [comment]
This has been fixed in https://github.com/firegento/firegento-magesetup2/pull/136.
