### ISSUE TITLE
Translation of delivery_time label

### ISSUE THREAD

**Issue by DanieliMi** [firegento/firegento-magesetup2#124]
### General

* Module version: 2.0.1
* Magento version: 2.2.6
* PHP version: 7.0.32

### Issue description

The translation of the label for delivery time is managed over the dictionary translation as of #74. But isn't it better to stay closer to magento and use the Manage Labels functionality?

The label [here](https://github.com/firegento/firegento-magesetup2/blob/4ee4cdfd06896776ea3cfa1378d46cbef068d91c/view/frontend/layout/catalog_product_view.xml#L16) needs to be changed to "default" in order to use magentos functionality.

**Comment by amenk** [comment]
Does anybody have an idea for this?

**Comment by amenk** [comment]
Not to confuse with #80

**Comment by amenk** [comment]
vendor/firegento/magesetup2/view/frontend/templates/product/list/delivery.phtml:25

    if ($_attributeLabel && $_attributeLabel == 'default') {
         $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
    }

I found this code ... it looks like in 

vendor/firegento/magesetup2/view/frontend/layout/catalog_delivery_info.xml:14

we just have to use the label "default" and it would work?

Why not just set this default as default?

**Comment by codedge** [comment]
This still is an issue in the recent version :(

**Comment by itsolon** [comment]
Is there any update.?
i have Delivery Time at product listing activated, but doing so .. no translate csv is drawn wherever i try to put the text in
i tried, in attribute itself
in i18n folder from vendor firegento already is the text inside works only for prodcut detail page
in i18n from my template as last measure does not work
thats all
i could alter the file delivery 
the easiest way is to switch of this functionality 
but you worked it in so lets perhaps use it?

I know you seo freaks out there you think now .. if he switches on then the seo strength of my keywors is washed out because of the use of hundreds delivery time haha.
best Regards 
Markus

**Comment by sprankhub** [comment]
I tend to replace "Delivery Time" here:

https://github.com/firegento/firegento-magesetup2/blob/fbcf4e2682992b49cf605e5acaf046d9b5203617/view/frontend/layout/catalog_product_view.xml#L16

with `default`, so that the label comes from the backend. However, this could mean that many German shops have the word in English on their product page after the next MageSetup update. They would need to manually change the label in the backend. I am fine with it, but I do not want to decide it on my own :) @firegento/magesetup2-maintainers, what do you think?

**Comment by frostblogNet** [comment]
I`m fine with that too.
