### ISSUE TITLE
Problem with mage:setup:run 

### ISSUE THREAD

**Issue by scriptserv** [firegento/firegento-magesetup2#13]
Hi,
i've got a problem with the setup:

I typed into the cmd the following code:
`php -f bin/magento magesetup:setup:run de `
(tried without -f too)

Everything is fine till
"Start processor: tax"

After that line appears nothing is going to happen - waited over 30 Mins.

Some info:
Clean install -> MageSetup is the first thing i wanted to install
System is local

**Comment by scriptserv** [comment]
Update: Waited for over 1,5 Hours - then the installation finished.

New Problem: The language dont change to German...

**Comment by therouv** [comment]
@scriptserv MageSetup changes the product taxclass during setup. Depending on the amount of products, this can take some time. Glad it works now for you.

MageSetup does not provide a German language pack. It only configures Magento2 for the German market.

I am closing this issue because the setup went through. Please feel free to open another issue if you encounter any other problems.
