### ISSUE TITLE
Detail Information in Checkout only in 'shipping' Page

### ISSUE THREAD

**Issue by JoergLindner** [firegento/firegento-magesetup2#130]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 0.1.1
* Magento version: 2.2.7
* PHP version: 7.0.6

### Issue description
While adding a product which has several Attribute set to 'visible in Checkout' it will show the attributes in the 'shipping screen of the checkout.
![image](https://user-images.githubusercontent.com/32593660/53116342-c45f2d00-3548-11e9-812b-28f010acb6a7.png)
but if forward to the payment page it just shows the 'Typ'. But here it is the most important part to have it.
![image](https://user-images.githubusercontent.com/32593660/53116556-47808300-3549-11e9-9d0d-f7acecc70f95.png)
 
...

### Steps to reproduce

1. Generate Attributes with 'Visible in Checkout' enable
2. Add this to a Attribute set for a product 
3. Generate product and add a content to the attributes
4. Run normal Checkout

**Comment by HenKun** [comment]
The problem is that the plugin responsible for adding the checkout attributes to the custom options is only applied for the `frontend` area. But required is the plugin also in the `webapi_rest` area.

To workaround the bug, as long as it is not included in the module:

1. Create a custom module
2. Copy `vendor/firegento/magesetup2/etc/frontend/di.xml` to your module under `/etc/webapi_rest/di.xml`

Et voila, everything works as expected.

**Comment by JoergLindner** [comment]
Why not just ad this to the module? Would do this as well?

**Comment by HenKun** [comment]
If you installed it via composer: you can't. It will be overriden on an update or on a clean install, since you don't have this change under version control.

If you installed by copying to app/code: you shouldn't. If you want to update the module you have to care for every change you did in the module. 

Just create a simple module under app/code and you are done.

**Comment by JoergLindner** [comment]
You are right, Better make a simple module

**Comment by sprankhub** [comment]
@HenKun thanks! Mind sending a pull request?

**Comment by HenKun** [comment]
Will be my first, I  will try my best these days. Are tests required?

**Comment by sprankhub** [comment]
Awesome! No, not required.
