### ISSUE TITLE
Error "Call to a member function getTaxPercent()" on Configurable Product Page

### ISSUE THREAD

**Issue by pamiec** [firegento/firegento-magesetup2#153]
### General

* Module version: 2.0.1
* Magento version: 2.3.3
* PHP version: 7.3

### Issue description
Configurabke Product Page gives this Error:

`Fatal error: Uncaught Error: Call to a member function getTaxPercent() on null in /var/www/vhosts/website.com/httpdocs/vendor/firegento/magesetup2/Block/Price/Details.php:159 Stack trace: #0 /var/www/vhosts/website.com/httpdocs/vendor/firegento/magesetup2/Block/Price/Details.php(96): FireGento\MageSetup\Block\Price\Details->getTaxPercentBySaleableItem() #1 [internal function]: FireGento\MageSetup\Block\Price\Details->getFormattedTaxRate() #2 /var/www/vhosts/website.com/httpdocs/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array) #3 /var/www/vhosts/website.com/httpdocs/app/design/frontend/econsor/ML/FireGento_MageSetup/templates/product/price/details.phtml(12): Magento\Framework\View\TemplateEngine\Php->__call('getFormattedTax...', Array) #4 /var/www/vhosts/website.com/httpdocs/vendor/magento/framework/View/TemplateEngin in /var/www/vhosts/website.com/httpdocs/vendor/firegento/magesetup2/Block/Price/Details.php on line 159`

### Steps to reproduce

1. Create Configurable Product
2. Add Simple Product to Configurable
3. Go to Product Page

This happens after i updated from 2.1.12 to 2.3.3, and PHP 7.0 to 7.3.
I tried deleting the Module and reinstall it. and ded the magesetup command.

**Comment by sprankhub** [comment]
What is your configuration value for `catalog/price/display_block_below_price`?

**Comment by pamiec** [comment]
Do you mean this setting in backend?

![backendsett](https://user-images.githubusercontent.com/55427697/76393968-f5d5b100-6374-11ea-9b02-a2d9cc602ac0.png)

it was set to "yes", but I have now set it to no, unfortunately it did not work. i also did reindex/cache clean...

**Comment by sprankhub** [comment]
This sounds pretty strange. And it is pretty hard to debug from here :-) I cannot reproduce this. Some things you could check:

* Please check if there are any plugins for `Magento\Framework\Pricing\Render` besides the one from MageSetup.
* Please check if this also happens if you use the standard theme and not your custom one.
* Please check if you have matches for the string `price_details` outside MageSetup.
* Please check the `reference` of `firegento/magesetup2` in your `composer.lock` and post it here.

**Comment by pamiec** [comment]
Thanks for your help. could find the cause of the problem. it has nothing to do with your extension.

**Comment by OvalMedia** [comment]
@pamiec : I am having the same issue. What was the cause in your case?

It might be a good idea to check if `saleableItem` is not null before proceeding in `getTaxPercentBySaleableItem()`
In my case sometimes saleableItem is null for reasons I still don't understand. In production mode this is immediately fixed by a reindex but this is less than optimal.
