### ISSUE TITLE
Order review on mobile

### ISSUE THREAD

**Issue by niclashoyer** [firegento/firegento-magesetup2#49]
The order review on mobile is problematic, at least regarding German laws. German law requires that the order review summary including the actual order total is visible next to the order submit button. However the order summary is hidden on mobile devices, because the order submit button is now located at the payment information:

![bildschirmfoto von 2016-11-24 16-13-49](https://cloud.githubusercontent.com/assets/175808/20603267/08ab1784-b261-11e6-8f3f-008233e519a1.png)

Has somebody looked at this problem, yet? I think the best solution would be to replace the "place order" button with a button "next" that would open the order summary, and below that one can place the order. Unfortunately the order submit button is hardcoded in every payment template.

**Comment by roman204** [comment]
The order summary have to be above the "order now" button. Maybe its possible to handle that problem via layout update?!?

**Comment by frostblogNet** [comment]
This problem is due to the way magento has build the checkout. You might get closer to a german solution by changing the view for "Display Billing Address On" to "Payment Page". You will find this setting under Configuration -> Sale -> Checkout -> Checkout option. But this is a magento not a magesetup issue.
