### ISSUE TITLE
One or more integrations have been reset because of a change to their xml configs.

### ISSUE THREAD

**Issue by Volle83** [firegento/firegento-magesetup2#84]
### General

* Module version: newest from github, running as de
* Magento version: 2.2.0
* PHP version: 7.1

### Issue description

After installing firegento as written in the manuel, on every backend page is the hint: `One or more integrations have been reset because of a change to their xml configs.`  But there is no entry of firegento in the integrations-list.

**Comment by Ralfefernandes** [comment]
I have also the same issues

**Comment by mnuhell** [comment]
I have also the same issues after update 2.1.9 to 2.2.0

i think it's a bug

**Comment by hezide** [comment]
same here

**Comment by sweetlearn** [comment]
the same !!!

**Comment by mautz-et-tong** [comment]
Closed.
This is due to some Social Module added in 2.2.0. This is Magento Core.
http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html#highlights

Long story short: They forced insert an API User named "Social Media". If you are not interested in using it, just delete the Integration Account "Social Media" from DB. (delete from integration where name = "Magento Social"; )
